In [20]:
import numpy as np
import time

In [109]:
matrix_1 = np.random.randint(10, size=(100, 100))
matrix_2 = np.random.randint(10, size=(100, 100))

In [110]:
%timeit np.dot(matrix_1, matrix_2)

1.27 ms ± 2.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [111]:
start_time = time.time()
res_np = np.dot(matrix_1, matrix_2)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0019965171813964844 seconds ---


In [112]:
print(res_np)

[[1843 2156 1800 ... 1719 1862 1711]
 [2240 2515 2117 ... 2047 2160 1840]
 [2157 2535 2102 ... 1931 2064 1915]
 ...
 [1684 2310 1758 ... 1674 1716 1702]
 [1952 2106 1906 ... 1884 1940 1746]
 [1876 2191 1956 ... 1835 1959 1758]]


In [119]:
def multiply_m(A, B):
    l_A = len(A)
    l_B = len(B)
    result=[[0 for j in range  (0 , l_A)] for i in range (0 , l_B)]
    for i in range(l_A): 
        for k in range(l_B): 
            r = A[i][k]
            for j in range(len(B[0])): 
                result[i][j] += r * B[k][j]
    return result

In [128]:
%timeit multiply_m(matrix_1, matrix_2)

885 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [127]:
start_time = time.time()
res_my = multiply_m(matrix_1, matrix_2)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.8733055591583252 seconds ---
